#!/bin/bash -ex

pushd ./rke

cat <<MAIN > main-vars.tfvars
aws_access_key = "${AWS_ACCESS_KEY_ID}"
aws_secret_key = "${AWS_SECRET_ACCESS_KEY}"
aws_region = "${AWS_DEFAULT_REGION}"
rke_cluster_name = "${RKE_CLUSTER_NAME}"
MAIN

popd
